language: node_js

node_js:
  - "0.10"

before_install:
  - sudo apt-get update
  - sudo apt-get install docker.io
  - sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
  - sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io